service: quotes
frameworkVersion: '>=1.28.8'
provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  stage: ${opt:stage}
functions:
  api:
    handler: bin/main
    events:
      - http:
          path: /api/head
          method: GET
package:
  patterns:
    - '!*/**'
    - bin/main
  


