// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/np_library.proto

package AIProto;

public final class NpLibrary {
  private NpLibrary() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NDArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AIProto.NDArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 shape = 1;</code>
     * @return A list containing the shape.
     */
    java.util.List<java.lang.Integer> getShapeList();
    /**
     * <code>repeated int32 shape = 1;</code>
     * @return The count of shape.
     */
    int getShapeCount();
    /**
     * <code>repeated int32 shape = 1;</code>
     * @param index The index of the element to return.
     * @return The shape at the given index.
     */
    int getShape(int index);

    /**
     * <code>float dtype = 2;</code>
     * @return The dtype.
     */
    float getDtype();

    /**
     * <code>.google.protobuf.Any buffer = 3;</code>
     * @return Whether the buffer field is set.
     */
    boolean hasBuffer();
    /**
     * <code>.google.protobuf.Any buffer = 3;</code>
     * @return The buffer.
     */
    com.google.protobuf.Any getBuffer();
    /**
     * <code>.google.protobuf.Any buffer = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getBufferOrBuilder();

    /**
     * <code>.google.protobuf.Any offset = 4;</code>
     * @return Whether the offset field is set.
     */
    boolean hasOffset();
    /**
     * <code>.google.protobuf.Any offset = 4;</code>
     * @return The offset.
     */
    com.google.protobuf.Any getOffset();
    /**
     * <code>.google.protobuf.Any offset = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getOffsetOrBuilder();

    /**
     * <code>.google.protobuf.Any strides = 5;</code>
     * @return Whether the strides field is set.
     */
    boolean hasStrides();
    /**
     * <code>.google.protobuf.Any strides = 5;</code>
     * @return The strides.
     */
    com.google.protobuf.Any getStrides();
    /**
     * <code>.google.protobuf.Any strides = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getStridesOrBuilder();

    /**
     * <code>.google.protobuf.Any order = 6;</code>
     * @return Whether the order field is set.
     */
    boolean hasOrder();
    /**
     * <code>.google.protobuf.Any order = 6;</code>
     * @return The order.
     */
    com.google.protobuf.Any getOrder();
    /**
     * <code>.google.protobuf.Any order = 6;</code>
     */
    com.google.protobuf.AnyOrBuilder getOrderOrBuilder();

    AIProto.NpLibrary.NDArray.InstrumentCase getInstrumentCase();
  }
  /**
   * <pre>
   * NS Array kwargs with speical type.
   * </pre>
   *
   * Protobuf type {@code AIProto.NDArray}
   */
  public static final class NDArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AIProto.NDArray)
      NDArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NDArray.newBuilder() to construct.
    private NDArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NDArray() {
      shape_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NDArray();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AIProto.NpLibrary.internal_static_AIProto_NDArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AIProto.NpLibrary.internal_static_AIProto_NDArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AIProto.NpLibrary.NDArray.class, AIProto.NpLibrary.NDArray.Builder.class);
    }

    private int instrumentCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object instrument_;
    public enum InstrumentCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      BUFFER(3),
      OFFSET(4),
      STRIDES(5),
      ORDER(6),
      INSTRUMENT_NOT_SET(0);
      private final int value;
      private InstrumentCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InstrumentCase valueOf(int value) {
        return forNumber(value);
      }

      public static InstrumentCase forNumber(int value) {
        switch (value) {
          case 3: return BUFFER;
          case 4: return OFFSET;
          case 5: return STRIDES;
          case 6: return ORDER;
          case 0: return INSTRUMENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public InstrumentCase
    getInstrumentCase() {
      return InstrumentCase.forNumber(
          instrumentCase_);
    }

    public static final int SHAPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList shape_ =
        emptyIntList();
    /**
     * <code>repeated int32 shape = 1;</code>
     * @return A list containing the shape.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getShapeList() {
      return shape_;
    }
    /**
     * <code>repeated int32 shape = 1;</code>
     * @return The count of shape.
     */
    public int getShapeCount() {
      return shape_.size();
    }
    /**
     * <code>repeated int32 shape = 1;</code>
     * @param index The index of the element to return.
     * @return The shape at the given index.
     */
    public int getShape(int index) {
      return shape_.getInt(index);
    }
    private int shapeMemoizedSerializedSize = -1;

    public static final int DTYPE_FIELD_NUMBER = 2;
    private float dtype_ = 0F;
    /**
     * <code>float dtype = 2;</code>
     * @return The dtype.
     */
    @java.lang.Override
    public float getDtype() {
      return dtype_;
    }

    public static final int BUFFER_FIELD_NUMBER = 3;
    /**
     * <code>.google.protobuf.Any buffer = 3;</code>
     * @return Whether the buffer field is set.
     */
    @java.lang.Override
    public boolean hasBuffer() {
      return instrumentCase_ == 3;
    }
    /**
     * <code>.google.protobuf.Any buffer = 3;</code>
     * @return The buffer.
     */
    @java.lang.Override
    public com.google.protobuf.Any getBuffer() {
      if (instrumentCase_ == 3) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Any buffer = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getBufferOrBuilder() {
      if (instrumentCase_ == 3) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }

    public static final int OFFSET_FIELD_NUMBER = 4;
    /**
     * <code>.google.protobuf.Any offset = 4;</code>
     * @return Whether the offset field is set.
     */
    @java.lang.Override
    public boolean hasOffset() {
      return instrumentCase_ == 4;
    }
    /**
     * <code>.google.protobuf.Any offset = 4;</code>
     * @return The offset.
     */
    @java.lang.Override
    public com.google.protobuf.Any getOffset() {
      if (instrumentCase_ == 4) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Any offset = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getOffsetOrBuilder() {
      if (instrumentCase_ == 4) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }

    public static final int STRIDES_FIELD_NUMBER = 5;
    /**
     * <code>.google.protobuf.Any strides = 5;</code>
     * @return Whether the strides field is set.
     */
    @java.lang.Override
    public boolean hasStrides() {
      return instrumentCase_ == 5;
    }
    /**
     * <code>.google.protobuf.Any strides = 5;</code>
     * @return The strides.
     */
    @java.lang.Override
    public com.google.protobuf.Any getStrides() {
      if (instrumentCase_ == 5) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Any strides = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getStridesOrBuilder() {
      if (instrumentCase_ == 5) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }

    public static final int ORDER_FIELD_NUMBER = 6;
    /**
     * <code>.google.protobuf.Any order = 6;</code>
     * @return Whether the order field is set.
     */
    @java.lang.Override
    public boolean hasOrder() {
      return instrumentCase_ == 6;
    }
    /**
     * <code>.google.protobuf.Any order = 6;</code>
     * @return The order.
     */
    @java.lang.Override
    public com.google.protobuf.Any getOrder() {
      if (instrumentCase_ == 6) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Any order = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getOrderOrBuilder() {
      if (instrumentCase_ == 6) {
         return (com.google.protobuf.Any) instrument_;
      }
      return com.google.protobuf.Any.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getShapeList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(shapeMemoizedSerializedSize);
      }
      for (int i = 0; i < shape_.size(); i++) {
        output.writeInt32NoTag(shape_.getInt(i));
      }
      if (java.lang.Float.floatToRawIntBits(dtype_) != 0) {
        output.writeFloat(2, dtype_);
      }
      if (instrumentCase_ == 3) {
        output.writeMessage(3, (com.google.protobuf.Any) instrument_);
      }
      if (instrumentCase_ == 4) {
        output.writeMessage(4, (com.google.protobuf.Any) instrument_);
      }
      if (instrumentCase_ == 5) {
        output.writeMessage(5, (com.google.protobuf.Any) instrument_);
      }
      if (instrumentCase_ == 6) {
        output.writeMessage(6, (com.google.protobuf.Any) instrument_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < shape_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(shape_.getInt(i));
        }
        size += dataSize;
        if (!getShapeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        shapeMemoizedSerializedSize = dataSize;
      }
      if (java.lang.Float.floatToRawIntBits(dtype_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, dtype_);
      }
      if (instrumentCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.google.protobuf.Any) instrument_);
      }
      if (instrumentCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.google.protobuf.Any) instrument_);
      }
      if (instrumentCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (com.google.protobuf.Any) instrument_);
      }
      if (instrumentCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (com.google.protobuf.Any) instrument_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AIProto.NpLibrary.NDArray)) {
        return super.equals(obj);
      }
      AIProto.NpLibrary.NDArray other = (AIProto.NpLibrary.NDArray) obj;

      if (!getShapeList()
          .equals(other.getShapeList())) return false;
      if (java.lang.Float.floatToIntBits(getDtype())
          != java.lang.Float.floatToIntBits(
              other.getDtype())) return false;
      if (!getInstrumentCase().equals(other.getInstrumentCase())) return false;
      switch (instrumentCase_) {
        case 3:
          if (!getBuffer()
              .equals(other.getBuffer())) return false;
          break;
        case 4:
          if (!getOffset()
              .equals(other.getOffset())) return false;
          break;
        case 5:
          if (!getStrides()
              .equals(other.getStrides())) return false;
          break;
        case 6:
          if (!getOrder()
              .equals(other.getOrder())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getShapeCount() > 0) {
        hash = (37 * hash) + SHAPE_FIELD_NUMBER;
        hash = (53 * hash) + getShapeList().hashCode();
      }
      hash = (37 * hash) + DTYPE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDtype());
      switch (instrumentCase_) {
        case 3:
          hash = (37 * hash) + BUFFER_FIELD_NUMBER;
          hash = (53 * hash) + getBuffer().hashCode();
          break;
        case 4:
          hash = (37 * hash) + OFFSET_FIELD_NUMBER;
          hash = (53 * hash) + getOffset().hashCode();
          break;
        case 5:
          hash = (37 * hash) + STRIDES_FIELD_NUMBER;
          hash = (53 * hash) + getStrides().hashCode();
          break;
        case 6:
          hash = (37 * hash) + ORDER_FIELD_NUMBER;
          hash = (53 * hash) + getOrder().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AIProto.NpLibrary.NDArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static AIProto.NpLibrary.NDArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static AIProto.NpLibrary.NDArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AIProto.NpLibrary.NDArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AIProto.NpLibrary.NDArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * NS Array kwargs with speical type.
     * </pre>
     *
     * Protobuf type {@code AIProto.NDArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AIProto.NDArray)
        AIProto.NpLibrary.NDArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AIProto.NpLibrary.internal_static_AIProto_NDArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AIProto.NpLibrary.internal_static_AIProto_NDArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AIProto.NpLibrary.NDArray.class, AIProto.NpLibrary.NDArray.Builder.class);
      }

      // Construct using AIProto.NpLibrary.NDArray.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        shape_ = emptyIntList();
        dtype_ = 0F;
        if (bufferBuilder_ != null) {
          bufferBuilder_.clear();
        }
        if (offsetBuilder_ != null) {
          offsetBuilder_.clear();
        }
        if (stridesBuilder_ != null) {
          stridesBuilder_.clear();
        }
        if (orderBuilder_ != null) {
          orderBuilder_.clear();
        }
        instrumentCase_ = 0;
        instrument_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AIProto.NpLibrary.internal_static_AIProto_NDArray_descriptor;
      }

      @java.lang.Override
      public AIProto.NpLibrary.NDArray getDefaultInstanceForType() {
        return AIProto.NpLibrary.NDArray.getDefaultInstance();
      }

      @java.lang.Override
      public AIProto.NpLibrary.NDArray build() {
        AIProto.NpLibrary.NDArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AIProto.NpLibrary.NDArray buildPartial() {
        AIProto.NpLibrary.NDArray result = new AIProto.NpLibrary.NDArray(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(AIProto.NpLibrary.NDArray result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          shape_.makeImmutable();
          result.shape_ = shape_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dtype_ = dtype_;
        }
      }

      private void buildPartialOneofs(AIProto.NpLibrary.NDArray result) {
        result.instrumentCase_ = instrumentCase_;
        result.instrument_ = this.instrument_;
        if (instrumentCase_ == 3 &&
            bufferBuilder_ != null) {
          result.instrument_ = bufferBuilder_.build();
        }
        if (instrumentCase_ == 4 &&
            offsetBuilder_ != null) {
          result.instrument_ = offsetBuilder_.build();
        }
        if (instrumentCase_ == 5 &&
            stridesBuilder_ != null) {
          result.instrument_ = stridesBuilder_.build();
        }
        if (instrumentCase_ == 6 &&
            orderBuilder_ != null) {
          result.instrument_ = orderBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AIProto.NpLibrary.NDArray) {
          return mergeFrom((AIProto.NpLibrary.NDArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AIProto.NpLibrary.NDArray other) {
        if (other == AIProto.NpLibrary.NDArray.getDefaultInstance()) return this;
        if (!other.shape_.isEmpty()) {
          if (shape_.isEmpty()) {
            shape_ = other.shape_;
            shape_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureShapeIsMutable();
            shape_.addAll(other.shape_);
          }
          onChanged();
        }
        if (other.getDtype() != 0F) {
          setDtype(other.getDtype());
        }
        switch (other.getInstrumentCase()) {
          case BUFFER: {
            mergeBuffer(other.getBuffer());
            break;
          }
          case OFFSET: {
            mergeOffset(other.getOffset());
            break;
          }
          case STRIDES: {
            mergeStrides(other.getStrides());
            break;
          }
          case ORDER: {
            mergeOrder(other.getOrder());
            break;
          }
          case INSTRUMENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureShapeIsMutable();
                shape_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureShapeIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  shape_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 21: {
                dtype_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 26: {
                input.readMessage(
                    getBufferFieldBuilder().getBuilder(),
                    extensionRegistry);
                instrumentCase_ = 3;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getOffsetFieldBuilder().getBuilder(),
                    extensionRegistry);
                instrumentCase_ = 4;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getStridesFieldBuilder().getBuilder(),
                    extensionRegistry);
                instrumentCase_ = 5;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getOrderFieldBuilder().getBuilder(),
                    extensionRegistry);
                instrumentCase_ = 6;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int instrumentCase_ = 0;
      private java.lang.Object instrument_;
      public InstrumentCase
          getInstrumentCase() {
        return InstrumentCase.forNumber(
            instrumentCase_);
      }

      public Builder clearInstrument() {
        instrumentCase_ = 0;
        instrument_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.Internal.IntList shape_ = emptyIntList();
      private void ensureShapeIsMutable() {
        if (!shape_.isModifiable()) {
          shape_ = makeMutableCopy(shape_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int32 shape = 1;</code>
       * @return A list containing the shape.
       */
      public java.util.List<java.lang.Integer>
          getShapeList() {
        shape_.makeImmutable();
        return shape_;
      }
      /**
       * <code>repeated int32 shape = 1;</code>
       * @return The count of shape.
       */
      public int getShapeCount() {
        return shape_.size();
      }
      /**
       * <code>repeated int32 shape = 1;</code>
       * @param index The index of the element to return.
       * @return The shape at the given index.
       */
      public int getShape(int index) {
        return shape_.getInt(index);
      }
      /**
       * <code>repeated int32 shape = 1;</code>
       * @param index The index to set the value at.
       * @param value The shape to set.
       * @return This builder for chaining.
       */
      public Builder setShape(
          int index, int value) {

        ensureShapeIsMutable();
        shape_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 shape = 1;</code>
       * @param value The shape to add.
       * @return This builder for chaining.
       */
      public Builder addShape(int value) {

        ensureShapeIsMutable();
        shape_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 shape = 1;</code>
       * @param values The shape to add.
       * @return This builder for chaining.
       */
      public Builder addAllShape(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureShapeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, shape_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 shape = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearShape() {
        shape_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private float dtype_ ;
      /**
       * <code>float dtype = 2;</code>
       * @return The dtype.
       */
      @java.lang.Override
      public float getDtype() {
        return dtype_;
      }
      /**
       * <code>float dtype = 2;</code>
       * @param value The dtype to set.
       * @return This builder for chaining.
       */
      public Builder setDtype(float value) {

        dtype_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float dtype = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dtype_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bufferBuilder_;
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       * @return Whether the buffer field is set.
       */
      @java.lang.Override
      public boolean hasBuffer() {
        return instrumentCase_ == 3;
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       * @return The buffer.
       */
      @java.lang.Override
      public com.google.protobuf.Any getBuffer() {
        if (bufferBuilder_ == null) {
          if (instrumentCase_ == 3) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        } else {
          if (instrumentCase_ == 3) {
            return bufferBuilder_.getMessage();
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       */
      public Builder setBuffer(com.google.protobuf.Any value) {
        if (bufferBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          instrument_ = value;
          onChanged();
        } else {
          bufferBuilder_.setMessage(value);
        }
        instrumentCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       */
      public Builder setBuffer(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bufferBuilder_ == null) {
          instrument_ = builderForValue.build();
          onChanged();
        } else {
          bufferBuilder_.setMessage(builderForValue.build());
        }
        instrumentCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       */
      public Builder mergeBuffer(com.google.protobuf.Any value) {
        if (bufferBuilder_ == null) {
          if (instrumentCase_ == 3 &&
              instrument_ != com.google.protobuf.Any.getDefaultInstance()) {
            instrument_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) instrument_)
                .mergeFrom(value).buildPartial();
          } else {
            instrument_ = value;
          }
          onChanged();
        } else {
          if (instrumentCase_ == 3) {
            bufferBuilder_.mergeFrom(value);
          } else {
            bufferBuilder_.setMessage(value);
          }
        }
        instrumentCase_ = 3;
        return this;
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       */
      public Builder clearBuffer() {
        if (bufferBuilder_ == null) {
          if (instrumentCase_ == 3) {
            instrumentCase_ = 0;
            instrument_ = null;
            onChanged();
          }
        } else {
          if (instrumentCase_ == 3) {
            instrumentCase_ = 0;
            instrument_ = null;
          }
          bufferBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       */
      public com.google.protobuf.Any.Builder getBufferBuilder() {
        return getBufferFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getBufferOrBuilder() {
        if ((instrumentCase_ == 3) && (bufferBuilder_ != null)) {
          return bufferBuilder_.getMessageOrBuilder();
        } else {
          if (instrumentCase_ == 3) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any buffer = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBufferFieldBuilder() {
        if (bufferBuilder_ == null) {
          if (!(instrumentCase_ == 3)) {
            instrument_ = com.google.protobuf.Any.getDefaultInstance();
          }
          bufferBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  (com.google.protobuf.Any) instrument_,
                  getParentForChildren(),
                  isClean());
          instrument_ = null;
        }
        instrumentCase_ = 3;
        onChanged();
        return bufferBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> offsetBuilder_;
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       * @return Whether the offset field is set.
       */
      @java.lang.Override
      public boolean hasOffset() {
        return instrumentCase_ == 4;
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       * @return The offset.
       */
      @java.lang.Override
      public com.google.protobuf.Any getOffset() {
        if (offsetBuilder_ == null) {
          if (instrumentCase_ == 4) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        } else {
          if (instrumentCase_ == 4) {
            return offsetBuilder_.getMessage();
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       */
      public Builder setOffset(com.google.protobuf.Any value) {
        if (offsetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          instrument_ = value;
          onChanged();
        } else {
          offsetBuilder_.setMessage(value);
        }
        instrumentCase_ = 4;
        return this;
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       */
      public Builder setOffset(
          com.google.protobuf.Any.Builder builderForValue) {
        if (offsetBuilder_ == null) {
          instrument_ = builderForValue.build();
          onChanged();
        } else {
          offsetBuilder_.setMessage(builderForValue.build());
        }
        instrumentCase_ = 4;
        return this;
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       */
      public Builder mergeOffset(com.google.protobuf.Any value) {
        if (offsetBuilder_ == null) {
          if (instrumentCase_ == 4 &&
              instrument_ != com.google.protobuf.Any.getDefaultInstance()) {
            instrument_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) instrument_)
                .mergeFrom(value).buildPartial();
          } else {
            instrument_ = value;
          }
          onChanged();
        } else {
          if (instrumentCase_ == 4) {
            offsetBuilder_.mergeFrom(value);
          } else {
            offsetBuilder_.setMessage(value);
          }
        }
        instrumentCase_ = 4;
        return this;
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       */
      public Builder clearOffset() {
        if (offsetBuilder_ == null) {
          if (instrumentCase_ == 4) {
            instrumentCase_ = 0;
            instrument_ = null;
            onChanged();
          }
        } else {
          if (instrumentCase_ == 4) {
            instrumentCase_ = 0;
            instrument_ = null;
          }
          offsetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       */
      public com.google.protobuf.Any.Builder getOffsetBuilder() {
        return getOffsetFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getOffsetOrBuilder() {
        if ((instrumentCase_ == 4) && (offsetBuilder_ != null)) {
          return offsetBuilder_.getMessageOrBuilder();
        } else {
          if (instrumentCase_ == 4) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any offset = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getOffsetFieldBuilder() {
        if (offsetBuilder_ == null) {
          if (!(instrumentCase_ == 4)) {
            instrument_ = com.google.protobuf.Any.getDefaultInstance();
          }
          offsetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  (com.google.protobuf.Any) instrument_,
                  getParentForChildren(),
                  isClean());
          instrument_ = null;
        }
        instrumentCase_ = 4;
        onChanged();
        return offsetBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> stridesBuilder_;
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       * @return Whether the strides field is set.
       */
      @java.lang.Override
      public boolean hasStrides() {
        return instrumentCase_ == 5;
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       * @return The strides.
       */
      @java.lang.Override
      public com.google.protobuf.Any getStrides() {
        if (stridesBuilder_ == null) {
          if (instrumentCase_ == 5) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        } else {
          if (instrumentCase_ == 5) {
            return stridesBuilder_.getMessage();
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       */
      public Builder setStrides(com.google.protobuf.Any value) {
        if (stridesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          instrument_ = value;
          onChanged();
        } else {
          stridesBuilder_.setMessage(value);
        }
        instrumentCase_ = 5;
        return this;
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       */
      public Builder setStrides(
          com.google.protobuf.Any.Builder builderForValue) {
        if (stridesBuilder_ == null) {
          instrument_ = builderForValue.build();
          onChanged();
        } else {
          stridesBuilder_.setMessage(builderForValue.build());
        }
        instrumentCase_ = 5;
        return this;
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       */
      public Builder mergeStrides(com.google.protobuf.Any value) {
        if (stridesBuilder_ == null) {
          if (instrumentCase_ == 5 &&
              instrument_ != com.google.protobuf.Any.getDefaultInstance()) {
            instrument_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) instrument_)
                .mergeFrom(value).buildPartial();
          } else {
            instrument_ = value;
          }
          onChanged();
        } else {
          if (instrumentCase_ == 5) {
            stridesBuilder_.mergeFrom(value);
          } else {
            stridesBuilder_.setMessage(value);
          }
        }
        instrumentCase_ = 5;
        return this;
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       */
      public Builder clearStrides() {
        if (stridesBuilder_ == null) {
          if (instrumentCase_ == 5) {
            instrumentCase_ = 0;
            instrument_ = null;
            onChanged();
          }
        } else {
          if (instrumentCase_ == 5) {
            instrumentCase_ = 0;
            instrument_ = null;
          }
          stridesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       */
      public com.google.protobuf.Any.Builder getStridesBuilder() {
        return getStridesFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getStridesOrBuilder() {
        if ((instrumentCase_ == 5) && (stridesBuilder_ != null)) {
          return stridesBuilder_.getMessageOrBuilder();
        } else {
          if (instrumentCase_ == 5) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any strides = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getStridesFieldBuilder() {
        if (stridesBuilder_ == null) {
          if (!(instrumentCase_ == 5)) {
            instrument_ = com.google.protobuf.Any.getDefaultInstance();
          }
          stridesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  (com.google.protobuf.Any) instrument_,
                  getParentForChildren(),
                  isClean());
          instrument_ = null;
        }
        instrumentCase_ = 5;
        onChanged();
        return stridesBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> orderBuilder_;
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       * @return Whether the order field is set.
       */
      @java.lang.Override
      public boolean hasOrder() {
        return instrumentCase_ == 6;
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       * @return The order.
       */
      @java.lang.Override
      public com.google.protobuf.Any getOrder() {
        if (orderBuilder_ == null) {
          if (instrumentCase_ == 6) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        } else {
          if (instrumentCase_ == 6) {
            return orderBuilder_.getMessage();
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       */
      public Builder setOrder(com.google.protobuf.Any value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          instrument_ = value;
          onChanged();
        } else {
          orderBuilder_.setMessage(value);
        }
        instrumentCase_ = 6;
        return this;
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       */
      public Builder setOrder(
          com.google.protobuf.Any.Builder builderForValue) {
        if (orderBuilder_ == null) {
          instrument_ = builderForValue.build();
          onChanged();
        } else {
          orderBuilder_.setMessage(builderForValue.build());
        }
        instrumentCase_ = 6;
        return this;
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       */
      public Builder mergeOrder(com.google.protobuf.Any value) {
        if (orderBuilder_ == null) {
          if (instrumentCase_ == 6 &&
              instrument_ != com.google.protobuf.Any.getDefaultInstance()) {
            instrument_ = com.google.protobuf.Any.newBuilder((com.google.protobuf.Any) instrument_)
                .mergeFrom(value).buildPartial();
          } else {
            instrument_ = value;
          }
          onChanged();
        } else {
          if (instrumentCase_ == 6) {
            orderBuilder_.mergeFrom(value);
          } else {
            orderBuilder_.setMessage(value);
          }
        }
        instrumentCase_ = 6;
        return this;
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       */
      public Builder clearOrder() {
        if (orderBuilder_ == null) {
          if (instrumentCase_ == 6) {
            instrumentCase_ = 0;
            instrument_ = null;
            onChanged();
          }
        } else {
          if (instrumentCase_ == 6) {
            instrumentCase_ = 0;
            instrument_ = null;
          }
          orderBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       */
      public com.google.protobuf.Any.Builder getOrderBuilder() {
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getOrderOrBuilder() {
        if ((instrumentCase_ == 6) && (orderBuilder_ != null)) {
          return orderBuilder_.getMessageOrBuilder();
        } else {
          if (instrumentCase_ == 6) {
            return (com.google.protobuf.Any) instrument_;
          }
          return com.google.protobuf.Any.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Any order = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          if (!(instrumentCase_ == 6)) {
            instrument_ = com.google.protobuf.Any.getDefaultInstance();
          }
          orderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  (com.google.protobuf.Any) instrument_,
                  getParentForChildren(),
                  isClean());
          instrument_ = null;
        }
        instrumentCase_ = 6;
        onChanged();
        return orderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AIProto.NDArray)
    }

    // @@protoc_insertion_point(class_scope:AIProto.NDArray)
    private static final AIProto.NpLibrary.NDArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AIProto.NpLibrary.NDArray();
    }

    public static AIProto.NpLibrary.NDArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NDArray>
        PARSER = new com.google.protobuf.AbstractParser<NDArray>() {
      @java.lang.Override
      public NDArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NDArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NDArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AIProto.NpLibrary.NDArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AIProto_NDArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AIProto_NDArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024lib/np_library.proto\022\007AIProto\032\031google/" +
      "protobuf/any.proto\"\325\001\n\007NDArray\022\r\n\005shape\030" +
      "\001 \003(\005\022\r\n\005dtype\030\002 \001(\002\022&\n\006buffer\030\003 \001(\0132\024.g" +
      "oogle.protobuf.AnyH\000\022&\n\006offset\030\004 \001(\0132\024.g" +
      "oogle.protobuf.AnyH\000\022\'\n\007strides\030\005 \001(\0132\024." +
      "google.protobuf.AnyH\000\022%\n\005order\030\006 \001(\0132\024.g" +
      "oogle.protobuf.AnyH\000B\014\n\ninstrumentB\004Z\002./" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_AIProto_NDArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AIProto_NDArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AIProto_NDArray_descriptor,
        new java.lang.String[] { "Shape", "Dtype", "Buffer", "Offset", "Strides", "Order", "Instrument", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
