service: quotes

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

functions:
  api:
    handler: bin/main
    events:
      - httpApi: '*'
                                                                                                                                                         
package:
  patterns:
    - '!*/**'
    - bin/main
  


