service: quotes

frameworkVersion: '3'

provider:
  name: aws
  runtime: dotnetcore3.1

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: DotNetServerless.Lambda::DotNetServerless.Lambda.Functions.GetHeadFunction::Run
    events:
      - http:
          path: api
          method: /api/head
          cors: true

